apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: backend-rolebinding
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: dev
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
