apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: frontend
      port: 5173
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer