version: "3.8"
services:
  mysql:
    build: ./database
    image: fowx/cloudproject_database:my_db2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KarmaFowx27062018!
      MYSQL_DATABASE: clouddatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - app-network

  backend:
    build: ./backend
    image: fowx/cloudproject_api:my_api2
    container_name: spring_api
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/clouddatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: fowx/cloudproject_frontend:my_front2
    container_name: vue_front
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
