apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-admin-binding
  namespace: dev
subjects:
  - kind: User
    name: Jules
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Vadim
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-pod-reader-binding
subjects:
  - kind: User
    name: Alice
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Eleonore
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-service-manager-binding
subjects:
  - kind: User
    name: Michel
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: Arthur
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-service-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-configmap-manager-binding
subjects:
  - kind: User
    name: Celia
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-configmap-manager
  apiGroup: rbac.authorization.k8s.io
